INSERT INTO blogful_articles (title, content, date_published)
VALUES
    ('An Hour in a Day', 'kalsjd;lfajsd;lkfjas;ldkfja;sdlfkjasd;l', 1/23/2000),
    ('Many Other Hours', 'akjsdhflkashdfkashfiashdkhasdkfjhalskdfjh', 1/23/2001),
    ('The Minutes in an Hour', 'aksdjhfashdfkjashdfkljashdfkljashdflk', 1/23/2002),
    ('Whats an Hour?', 'ksajdhkashfkasjhdlkajshdlkasjdh', 1/23/2003),
    ('Hours in a Day', 'akjsdhfkljashdfklahslfksh', 1/23/2004),
    ('A Day Full of Hours', 'kskjshdkljahsdkfjhas', 1/23/2005),
    ('Whats with All the Hours?', 'kasjhdkljahsdkljhasdkfjhsdklfjhasldkjhsaldkjh', 1/23/2006),
    ('Hours and Hours and Hours', 'jakhsdkhaskhsdkjfhaskdjbnknv', 1/23/2007),
    ('Minutes and Hours and Minutes', 'kjshdafkjhsdkjhsdkjf', 1/23/2008),
    ('Just Minutes', 'aksdjhfkajshdflkajhsd', 1/23/2009),
    ('Just Hours', 'aksjdhfkajshdfkashdlkfjahsd', 1/23/2010),
    ('Just a Day', 'sajdhkhsdklhsdkjhsdkjf', 1/23/2011),
    ('I Wish I Had More Time', 'kjasdkljahsdfkjhaslkdjf', 1/23/2012),
    ('Time Keeps on Slipping...', 'askdjhfkjahsdflkjhasldkfj', 1/23/2013),
    ('...Into the Future...', 'kajsdkajhsdkfljhaskldjhasd', 1/23/2014),
    ('Tick, Tock, Tick, Tock...', 'kjasdhkjhasdklfjhasdf', 1/23/2015),
    ('The Hands on the Clock Go Round and Round', 'aksjdhkjasdhfklasjdhflkasd', 1/23/2016),
    ('Is It Noon Yet?!', 'kajshdfkjahsdkfhaslkdf', 1/23/2017),
    ('Are We There Yet?!', 'askjdhfkjahsdlfkjahsdlkfjhasd', 1/23/2018),
    ('The Day is Done.', 'aksjdhkjahsdkjahsdlkhsldkjfhalskdjhlaksdjhflskjdhlskdjfhlasdkj', 1/23/2019),